### ISSUE TITLE
Deprecated: auto_detect_line_endings is deprecated

### ISSUE THREAD

**Issue by Bernier154** [JackieDo/Xampp-vHosts-Manager#5]
The ini_set directive at line 17 of src/helpers.php issue a warning in the console on php 8.1.

Link to php changelog : https://www.php.net/manual/fr/migration81.deprecated.php#migration81.deprecated.standard

The php documentation cite: 

> The [auto_detect_line_endings](https://www.php.net/manual/fr/filesystem.configuration.php#ini.auto-detect-line-endings) INI directive is deprecated. If necessary, handle "\r" line breaks manually instead.

Personally i just removed the lines in my installation because i'm running on a recent windows machine.

**Comment by JackieDo** [comment]
@Bernier154 :
This problem is resolved in the release [v1.0.6](https://github.com/JackieDo/Xampp-vHosts-Manager/releases/tag/1.0.6). You can down load source code and override the `helper.php` file (in the `src` folder).
